[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
Color
ILoveCandy
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[Include]
Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
